### ISSUE TITLE
The engine is not actually switched!

### ISSUE THREAD

**Issue by MGG1996** [isteinbrecher/latex2ai#162] opened 2024-10-16 12:38 UTC
In Windows platform, the version v1.0.0-rc.1 seems to have a serious bug.

In the configuration page, i have switched the engine from pdflatex to xelatex and pressed the save button, but it doesnt really take effect.

Each time  i write a new equation, it still run and compile with pdflatex, this can be proved with the log file.

Even the old equations that generated by LaTex2AI v0.0.1 cannot get through regeneration.

**Comment by MGG1996** [comment] 2024-10-16 13:09
I guess i have already located where the problem is.

After several attempts, i deleted the path settings for " folder for the latex executables" and leave it blank just as i did in v0.0.1. Surprisingly, it works.

When i set this again, errors appear again. I promise that i have entered the correct path for this parameter, just like the configuration in my environment variables.

It's so wierd, hahaha.

**Comment by MGG1996** [comment] 2024-10-18 01:15
Greetings isteinbrecher. Thank you for your reply.

I have attempted the new commit, the bug has been fixed successfully. Thanks for your effort!

Meanwhile, I noticed some other phenomena: If there are errors in the formula, the commit will not raise an error window again, but will directly use the result of the last successful compilation. Additionally, sometimes after successful compilation, AI will automatically shrink to the taskbar. I don't know if these phenomena are normal.

**Comment by MGG1996** [comment] 2024-10-18 01:28
I would like to correct the above phenomenon. After successful compilation, AI did not shrink to the taskbar, but was placed at the bottom of all desktop windows.

**Comment by MGG1996** [comment] 2024-10-19 03:10
Thanks for your quick response. Successful compilations no longer hide the AI window behand all other opened windows in the new commit.

As you asked, I prefer to have an error window popped up when there are compilation issues, as it allows me to easily troubleshoot the problem. Also, replacing the formula that was compiled incorrectly with the formula that was successfully compiled last time may require users to put more effort to check its correctness, which is particularly prominent when there is little difference between adjacent formulas.

Additionally, I have some feedback based on my experience:

1. Is there any possible to set an option for the user to choose that whether "enter" or "shift+enter" should be used to produce line breaks in formulas. In most LaTeX formula editors, “enter” is the default line wrapping method. After LaTeX2AI changes and fixes it to “shift+enter”, the habitual behavior can easily lead to the initiation of compilations before the formula is fully edited. Maybe clicking the "OK" button to start compiling is more suitable for this group of users.

2. Is it possible to support the use of double "$" symbols in LaTeX to generate inter line formulas. I know we can use \displaystyle in LaTeX2AI to generate inter line formulas, but typing this command is usually not as efficient as typing "$$", and using this command explicitly also requires the users to change their habits.

I greatly appreciate your valuable work and hope that the above feedback would not overly disturb you.

**Comment by isteinbrecher** [comment] 2024-10-19 20:56
Good to hear that this now works. I will add this to the next release version, then this issue can be closed.

Also, thanks for your feedback!

> As you asked, I prefer to have an error window popped up when there are compilation issues, as it allows me to easily troubleshoot the problem. Also, replacing the formula that was compiled incorrectly with the formula that was successfully compiled last time may require users to put more effort to check its correctness, which is particularly prominent when there is little difference between adjacent formulas.

This should already be the case. If a "bad" LaTeX code is entered and the user selects  `Re-edit LaTeX code` the "bad" code should still be in the item form. If you want to go back to the old "good" code, you can close the item creation window and open it again than the old code should appear. (I just tried this on macOS, but should also be the case on Windows)

> Is there any possible to set an option for the user to choose that whether "enter" or "shift+enter" should be used to produce line breaks in formulas. In most LaTeX formula editors, “enter” is the default line wrapping method. After LaTeX2AI changes and fixes it to “shift+enter”, the habitual behavior can easily lead to the initiation of compilations before the formula is fully edited. Maybe clicking the "OK" button to start compiling is more suitable for this group of users.

This is a good point! This is not possible at the moment, but should not be so difficult to add, feel free to open an issue for this feature request.

> Is it possible to support the use of double "$" symbols in LaTeX to generate inter line formulas. I know we can use \displaystyle in LaTeX2AI to generate inter line formulas, but typing this command is usually not as efficient as typing "$$", and using this command explicitly also requires the users to change their habits.

This is unfortunately not possible due to the way LaTeX2AI items are created.

**Comment by MGG1996** [comment] 2024-10-20 01:53
Maybe I did not express myself clearly enough.

When I open AI and enter a project, I create the first formula with a wrong code, then compilation will raise an error and a little error window will pop up, where "Debug actions" are listed.

Then I click on the "re-edit latex code" button, and fix the code, the first formula then can be successfully compiled.

After that, I create the second formula, again with a wrong code. However, this time it will not raise any error, the little error window will not show , and neither does the "re-edit latex code" button. Instead, the second foumula will automatically close the item window and be shown just as a new image that has the same apperance as the first formula.

At this point, when I open the image corresponding to the second formula, the code inside is still the second one with errors, but its appearance does not match it.

Now, when I close this project without saving it, while still keep AI opened, and reopen the project, LaTeX2AI will raise an error reminder with a bigg window, just as the attached picture below.
![2024-10-20_092822](https://github.com/user-attachments/assets/f6e61a49-d0ba-40aa-8847-588a4d669a3e)

**Comment by isteinbrecher** [comment] 2024-10-20 11:46
Thanks for reporting this in detail, indeed there was a small bug introduced in the initial fix to this issue. I hope this is now finally fixed with 15838fe. @MGG1996 could you be so kind to try once again and check, if the initial issue is fixed _and_ the reported bug is not happening any more? Thanks!

[LaTeX2AI_15838fe.zip](https://github.com/user-attachments/files/17450067/LaTeX2AI_15838fe.zip)

**Comment by MGG1996** [comment] 2024-10-20 12:17
Mighty @isteinbrecher , I'm happy to tell you that the problem of compiling the wrong code does not be able to pop up the error window has been solved. And the issue that I initially reported has also been fixed.

While, it seems that the alert in the above image still appears when I keep the AI open, close the project, and reopen the project again. However, it seems that this warning like window doesn't really affect the normal use of LaTeX2AI.

Thanks for your endless patience.

**Comment by isteinbrecher** [comment] 2024-10-20 12:49
@MGG1996 good to hear that the initial issue is fixed!

I can't reproduce the other error you report (the alert window you posted). Can you try the following steps:
- Use a completely new document (maybe the other bug where bad LaTeX code still resulted in a LaTeX2AI item messed something up in your document - very unlikely, but just to be sure)
- Try to reproduce the error, with the current release `v1.0.0-rc.1` and the current fix for this issue `15838fe`?

If the bug was introduced with the current fix, lets figure out what goes wrong within this issue, otherwise, let's open another issue to track that bug. 

Also thanks to you for your patience!

**Comment by MGG1996** [comment] 2024-10-21 00:55
Hello @isteinbrecher, I have already made more tests again, and it seems that this problem was already there in v0.0.10.

I have opened a new issue, please move to #169 .

**Comment by isteinbrecher** [comment] 2024-10-21 18:55
Thanks! Then we can close this issue once the new release is published.

**Comment by isteinbrecher** [comment] 2024-11-29 13:51
With the release of _v1.0.0_ this issue can be closed. @MGG1996 thanks for reporting this.

**Closed by isteinbrecher** 2024-11-29 13:51 UTC
Labels: bug
